[package]
name = "begin-rust-07"
version = "0.1.0"
authors = ["Dominik Gruntz <dominik.gruntz@fhnw.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
